spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pushtools
    username: pushtools
    password: root
  mvc:
    static-path-pattern: /static/**
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mapper/**.xml

pushTools:
  api: https://api2.pushdeer.com

logging:
  level:
    root: debug
  file:
    path: logs
